### ISSUE TITLE
Bootstrap issues with Vagrant sandbox

### ISSUE THREAD

**Issue by stephenyeargin** [frymanio/mac_me#3]
- Vagrant 1.7.4
- VirtualBox 5.0.14 r105127

When following the steps in the README, I get this during `vagrant up`

```
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.22
    default: VirtualBox Version: 5.0
==> default: Setting hostname...
NFS requires a host-only network to be created.
Please add a host-only network to the machine (with either DHCP or a
static IP) for NFS to work.
```

Ignoring it and attempting to run the `script/bootstrap` yields:

```
script/bootstrap: line 11: fail-loud: command not found
```

Are there unstated dependencies?

**Comment by jfryman** [comment]
Add a host-only network. Does that work?

fwiw: I'm running VMWare Fusion, so I might need a PR with some VBox specific tweaks.

**Comment by stephenyeargin** [comment]
With patch:

```
diff --git a/Vagrantfile b/Vagrantfile
index f59d833..62d67ff 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -5,6 +5,10 @@ ROOT_DIR = "/opt/mac_me"
 BOX = "puppetlabs/debian-8.2-32-nocm"
 
 Vagrant.configure(2) do |config|
+  config.vm.provider "virtualbox" do |vb|
+    config.vm.network "private_network", :type => 'dhcp', :name => 'vboxnet0', :adapter => 2
+  end
+
   config.vm.box = BOX
   config.vm.hostname = "mac-me-dev"
   config.vm.network "forwarded_port", guest: 3890, host: 3890
```

It progressed further, but returned:

```
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 10.0.3.1:'/Users/stephen/Sites/mac_me' /vagrant

Stdout from the command:



Stderr from the command:

stdin: is not a tty
mount.nfs: access denied by server while mounting 10.0.3.1:/Users/stephen/Sites/mac_me
```

**Comment by jfryman** [comment]
Ok, so I removed NFS for the base mounts... 

https://github.com/frymanio/mac_me/commit/387797222711d461ea880bad9646d2b89d506e2b

How about now?

**Comment by stephenyeargin** [comment]
That seems to have fixed it. I'm a bit confused by the last step:

`script/cibuild`

Is that meant to be run on the host machine or within the vagrant box (e.g. `/opt/mac_me`)? At any rate, both ways returned roughly the same two test fails:

```
vagrant@mac-me-dev:/opt/mac_me$ script/cibuild
[log] Setting up test LDAP server...
25653
* creating /home/vagrant/.mix/archives/hex-0.11.1.ez
Running dependency resolution
All dependencies up to date
==> idna (compile)
==> ssl_verify_hostname (compile)
==> ranch (compile)
==> hackney (compile)
==> fs (compile)
==> cowlib (compile)
==> cowboy (compile)
[log] Running code ...
You have configured application :dogma in your configuration
file but the application is not available.

This usually means one of:

1. You have not added the application as a dependency in a mix.exs file.

2. You are configuring an application that does not really exist.

Please ensure :dogma exists or remove the configuration.

...21:28:51.366 [error] GenServer MacMe.LDAP.Connection terminating
** (stop) bad return value: {:state, {:ok, {:eldap_search_result, [{:eldap_entry, 'cn=test-user,ou=People,dc=example,dc=com', [{'objectClass', ['inetOrgPerson', 'organizationalPerson', 'person', 'top']}, {'sn', ['Test User']}, {'cn', ['test-user']}]}], []}}, %MacMe.LDAP.Connection.State{base_dn: "dc=example,dc=com", bind_dn: "cn=admin,dc=example,dc=com", handle: #PID<0.190.0>, hosts: ['127.0.0.1'], port: 3890, ssl: false}}
21:28:51.367 [error] GenServer MacMe.LDAP.Connection terminating
** (stop) bad return value: {:state, {:ok, {:eldap_search_result, [{:eldap_entry, 'ou=Groups,dc=example,dc=com', [{'objectClass', ['organizationalUnit', 'top']}, {'ou', ['groups ']}]}], []}}, %MacMe.LDAP.Connection.State{base_dn: "dc=example,dc=com", bind_dn: "cn=admin,dc=example,dc=com", handle: #PID<0.262.0>, hosts: ['127.0.0.1'], port: 3890, ssl: false}}


  1) test query data (MacMe.LDAP.ConnectionTest)
     test/ldap/connection_test.exs:9
     ** (exit) exited in: GenServer.call(MacMe.LDAP.Connection, {:search, 'cn=test-user,ou=People,dc=example,dc=com'}, 5000)
         ** (EXIT) bad return value: {:state, {:ok, {:eldap_search_result, [{:eldap_entry, 'cn=test-user,ou=People,dc=example,dc=com', [{'objectClass', ['inetOrgPerson', 'organizationalPerson', 'person', 'top']}, {'sn', ['Test User']}, {'cn', ['test-user']}]}], []}}, %MacMe.LDAP.Connection.State{base_dn: "dc=example,dc=com", bind_dn: "cn=admin,dc=example,dc=com", handle: #PID<0.190.0>, hosts: ['127.0.0.1'], port: 3890, ssl: false}}
     stacktrace:
       (elixir) lib/gen_server.ex:564: GenServer.call/3
       test/ldap/connection_test.exs:17

...

  2) test properly detects an object that exists in the db (HelperTest)
     test/ldap/helper_test.exs:32
     ** (exit) exited in: GenServer.call(MacMe.LDAP.Connection, {:search, 'ou=Groups,dc=example,dc=com'}, 5000)
         ** (EXIT) bad return value: {:state, {:ok, {:eldap_search_result, [{:eldap_entry, 'ou=Groups,dc=example,dc=com', [{'objectClass', ['organizationalUnit', 'top']}, {'ou', ['groups ']}]}], []}}, %MacMe.LDAP.Connection.State{base_dn: "dc=example,dc=com", bind_dn: "cn=admin,dc=example,dc=com", handle: #PID<0.262.0>, hosts: ['127.0.0.1'], port: 3890, ssl: false}}
     stacktrace:
       (elixir) lib/gen_server.ex:564: GenServer.call/3
       (mac_me) lib/mac_me/ldap/helper.ex:53: MacMe.LDAP.Helper.exists?/1
       test/ldap/helper_test.exs:33



Finished in 0.7 seconds (0.6s on load, 0.09s on tests)
8 tests, 2 failures

Randomized with seed 127603
```

**Comment by jfryman** [comment]
`script/cibuild` is meant to run inside the vagrant vm. If you wanna dig into how the command works the same way, you'll want to look at https://github.com/frymanio/mac_me/blob/master/script/helpers.d/project-helpers#L35

That gets called from the main script in https://github.com/frymanio/mac_me/blob/master/script/cibuild#L16. So, regardless of your entry point, you're going to make it to debian because the darwin bootstrap is more or less a shortcut to vagrant. https://github.com/frymanio/mac_me/blob/master/script/cibuild-os-darwin#L10

Something something functional bash. Giving it a shot.
